server:
  port: 8081
  servlet:
    context-path: /identity


spring:

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: identity-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: revertAccountMsg:com.booking.identityservice.event.ProfileRevertEvent

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=identity-service;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Thmt20021001.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  signerkey: 5517010be55559740935ff533f504ec82054e3b73df043a3a141578470ff13bc;
  valid-duration: 50000
  refreshable-duration: 100000
app:
  service:
    profile: http://localhost:8082/profile