server:
  port: 8082
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: revertAccountMsg:com.booking.profileservice.event.ProfileRevertEvent,notificationMsg:com.booking.profileservice.event.NotificationEvent

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Thmt20021001.

