server:
  port: 8085
  servlet:
    context-path: /order

spring:

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=order-service;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Thmt20021001.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.type.mapping: ticketStockMsg:com.booking.orderservice.event.TicketStockEvent, orderMsg:com.booking.orderservice.entity.Order

    consumer:
      group-id: order-group

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: "ticketStockMsg:com.booking.orderservice.event.TicketStockEvent, orderMsg:com.booking.orderservice.entity.Order"

app:
  profile:
    event: http://localhost:8084/event
