server:
  port: 8084
  servlet:
    context-path: /event

spring:

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=event-service;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Thmt20021001.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6319
      password: ""
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5
      connect-timeout: 30000

  jackson:
    serialization:
      indent-output: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: event-group

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: "ticketStockMsg:com.booking.eventservice.event.TicketStockEvent"

