server:
  port: 8084
  servlet:
    context-path: /event

spring:

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=event-service;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Thmt20021001.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  data:
    redis:
      host: 127.0.0.1
      port: 6319
      password: ""
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5
      connect-timeout: 30000

  jackson:
    serialization:
      indent-output: true

jwt:
  signerkey: 5517010be55559740935ff533f504ec82054e3b73df043a3a141578470ff13bc;
  valid-duration: 50000
  refreshable-duration: 100000
app:
  service:
    profile: http://localhost:8082/profile